### PR TITLE
Adds api implementation for the ADC

### PR DESCRIPTION
**Pull request by stephanh**
Also provides the analog channel mapping for the pins on the nrf51822.

I tried to follow the same approach as taken here https://github.com/stm32-rs/stm32f1xx-hal/blob/master/src/adc.rs.

### CODE REVIEW

**Comment by therealprof** [comment]
Very nice!

I don't think we need the feature gate for the nrf51822, we really only implemented everything for that particular chip so far and as far as I can see ADC should even work for all chips in the nRF51 family.

**Comment by stephanh** [comment]
The feature gate is only for the pin to channel mapping (unless I made a mistake). That should be specific to that chip?

The ADC api is there for all nrf51 chips.

**Comment by therealprof** [comment]
I just checked all chips in the nRF51 family, they all have the same ADC pins.

**Comment by stephanh** [comment]
That's convenient :smile:. I have removed the feature gate.

**Comment by stephanh** [comment]
@therealprof would it be possible to get a release with this PR? 😄

**Comment by therealprof** [comment]
Sure, but I’m traveling at the moment. This will take a day or so...

**Comment by therealprof** [comment]
Done.

**Pull request merged**
